### ISSUE TITLE
v1.0.4 missing Reflect.getOwnMetadata

### ISSUE THREAD

**Issue by cehoffman** [jdanyow/aurelia-bundle#1]
When trying to use the 1.0.4 tag it appears the change of polyfill results in a missing Reflect method.

```
system.js:4 Uncaught (in promise) Error: Reflect.getOwnMetadata is not a function
    Error loading https://cdn.rawgit.com/jdanyow/aurelia-bundle/v1.0.4/dist/aurelia-bundle.js
    Error loading https://cdn.rawgit.com/jdanyow/aurelia-bundle/v1.0.4/jspm_packages/npm/aurelia-bootstrapper@1.0.0-beta.1.2.0.js
    at Object.getOwn (https://cdn.rawgit.com/jdanyow/aurelia-bundle/v1.0.4/dist/aurelia-bundle.js:237:22)
    at Object.getOrCreateOwn (https://cdn.rawgit.com/jdanyow/aurelia-bundle/v1.0.4/dist/aurelia-bundle.js:243:29)
    at deco (https://cdn.rawgit.com/jdanyow/aurelia-bundle/v1.0.4/dist/aurelia-bundle.js:10605:41)
    at bindable (https://cdn.rawgit.com/jdanyow/aurelia-bundle/v1.0.4/dist/aurelia-bundle.js:10620:14)
    at https://cdn.rawgit.com/jdanyow/aurelia-bundle/v1.0.4/dist/aurelia-bundle.js:16984:14
    at Array.reduce (native)
    at _applyDecoratedDescriptor (https://cdn.rawgit.com/jdanyow/aurelia-bundle/v1.0.4/dist/aurelia-bundle.js:16983:41)
    at Object.<anonymous> (https://cdn.rawgit.com/jdanyow/aurelia-bundle/v1.0.4/dist/aurelia-bundle.js:17109:23)
    at d.execute (https://cdn.rawgit.com/jdanyow/aurelia-bundle/v1.0.4/jspm_packages/system.js:5:8886)
    at u (https://cdn.rawgit.com/jdanyow/aurelia-bundle/v1.0.4/jspm_packages/system.js:4:30024)
```

**Comment by cehoffman** [comment]
I'm trying to create a gist.run to show an issue for a bug and I'm using 1.0.3, but I thought I should try to use the newest bundle as the base.

**Comment by jdanyow** [comment]
try this gist- it has the latest bits:  https://gist.run/?id=7542e061bc940cde506b
